### PR TITLE
add favicon

### PR DESCRIPTION
**Pull request by jpkcambridge**
Out of our options, I think this is the best one.  But we could probably have a better asset file for this.

### CODE REVIEW

**Comment by mikec** [comment]
@jpkcambridge this one https://drive.google.com/file/d/1XaQmM5poQLq6joqoh552n6bNuJ4qqQjS/view?usp=sharing would probably be better, since it's just the logo without company name. Probably need to crop to a square too

**Comment by alexfigtree** [comment]
@jpkcambridge Can we remove the "level k" text at the bottom?

**Comment by alexfigtree** [comment]
@jpkcambridge I see mike beat me to the comment

**Comment by jpkcambridge** [comment]
@mikec @alexfigtree Take two.  Dimensions look a little weird.  But not sure how to fix since the K is not a square

**Comment by alexfigtree** [comment]
@jpkcambridge add margin to the top and bottom!

**Comment by jpkcambridge** [comment]
@alexfigtree I don't think I know how to do that with an image.  Do you?

**Comment by alexfigtree** [comment]
@jpkcambridge Try this image I just created: https://drive.google.com/drive/u/0/folders/1b7gsHPEhiv0hvxjLYuMzzSUKIps2XtF2

('Asset 1@3x_with_added_margin.png')

**Comment by jpkcambridge** [comment]
@alexfigtree I don't see that image in the folder?

**Comment by alexfigtree** [comment]
@jpkcambridge Looks good!

**Pull request merged**
